# SPDX-FileCopyrightText: 2024 The Booters Developers
#
# SPDX-License-Identifier: GPL-3.0-only

[package]
name = "uefi_x86_64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
